id = "debug"
version = "0.1.0"
namespace = "com.github.glassmc.debug"

[listeners]
initialize = [
    "DebugDumpTransformer",
    "DebugStandardTransformer"
]

[environment]
    [environment.has]
    all = "*"