id = "debug"
version = "0.1.0"
namespace = "com.github.glassmc.debug"

implementations = [
    "mixin"
]

[listeners]
initialize = [
    "DebugInitializeListener",
]

[environment]
    [environment.has]
    all = "*"